name: Docker Publish

on:
  # Schedule a daily build at 4 AM UTC
  schedule:
    - cron: '0 4 * * *'
  # Trigger on pushes to the main branch and version tags
  push:
    branches: [ "main", "dev" ]
    tags: [ 'v*.*.*' ]
  # Trigger on pull requests to the master branch
  pull_request:
    branches: [ "main", "dev" ]

env:
  # Define the Docker registry, defaulting to Docker Hub
  REGISTRY: ghcr.io
  # Use the GitHub repository name for the image name
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Docker buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log into Docker registry (Github) except on pull requests
      - name: Log into Github
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Step 4: Extract Docker metadata such as tags and labels
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Step 5: Build and push the Docker image, skip push on pull requests
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64/v8
